require: rubocop-rails

AllCops:
  Exclude:
    - db/**/*
    - node_modules/**/*
    - bin/**/*
    - vendor/**/*
    - lib/tasks/**/*
    - config/initializers/**/*
  TargetRubyVersion: 3.0.2

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Rails:
  Enabled: true

Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - app/views/*

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 1500

Metrics/BlockLength:
  Max: 35

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test

Rails/LexicallyScopedActionFilter:
  Enabled: false