require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - db/**/*
    - node_modules/**/*
    - bin/**/*
    - vendor/**/*
    - lib/tasks/**/*
    - config/initializers/**/*
    - config/environments/**/*
    - lib/templates/rails/jbuilder/**/*
    - app/assets/javascripts/**/*
    - app/assets/stylesheets/**/*
    - .gitignore
    - '**/*.jbuilder'
  TargetRubyVersion: 3.0.2

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Rails:
  Enabled: true

Naming/AccessorMethodName:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 40

Metrics/ClassLength:
  Max: 1500

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test

Rails/LexicallyScopedActionFilter:
  Enabled: false